on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10.11'

      - run: pip install -r requirements.txt

      - run: echo "Hola mundo, Gh action" && python -c "print('main.py import OK')"

      - run: npm i -g @railway/cli

      - env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service "social-music-api" --ci

  deploy:
    runs_on: ubuntu-latest
       - name: Install Railway CLI
       run: |
       curl -fsSL https://railway.app/install.sh | sh || {
       echo "First install attempt failed, trying alternative method..."
       curl -L https://github.com/railwayapp/cli/releases/latest/download/railway-linux-x86_64.tar.gz
       tar -xzf railway.tar.gz
       sudo mv railway /usr/local/bin/
       chmod +x /usr/local/bin/railway
     }

       if [ -d "$HOME/.railway/bin" ]; then
        echo "$HOME/.railway/bin" >> $GITHUB_PATH
        export PATH="$HOME/.railway/bin:$PATH"
        fi

       railway --version || railway version || echo "Railway CLI installed but version check failed"

       - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
       run: |
         echo "starting deployment..." \
         railway up --service "Social-Music" ||\
         railway up --service social-music ||\
         railway up --service web ||\
         railway up --service api ||\
         railway up --service app ||\
         railway up --service Social-Music ||\
         railway up --service social ||\
         railway up --service backend ||\
         (echo "creating new service and deploying" && railway up)